# Generated by Django 5.1.6 on 2025-03-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
