# Generated by Django 5.1.6 on 2025-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
