# Generated by Django 5.1.6 on 2025-03-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='author_name',
        ),
        migrations.AddField(
            model_name='requisition',
            name='author_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
