# Generated by Django 5.1.6 on 2025-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_order_payment_mode_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
